### ISSUE TITLE
i can't create an account with this

### ISSUE THREAD

**Issue by NineDesires** [xxCherry/hqosu-legacy#15]
the create an account button redirects to the old register website which is now gone

**Comment by MiclySlGa** [comment]
I don't understand what you're trying to say here.

**Comment by Kanaze-chan** [comment]
> I don't understand what you're trying to say here.

He's saying osu! just changed the way to register an account, which is you can only register in-game only and you are no longer to register on website.

**Comment by MiclySlGa** [comment]
Have you tired using a VPN And using the HQOsu one?
