### ISSUE TITLE
Opens Osu Update.

### ISSUE THREAD

**Issue by MiclySlGa** [xxCherry/hqosu-legacy#18]
When i open  hqosu.loader it opens up osu update and when it's done it does not inject hqosu in instead just open normal osu.

![image](https://user-images.githubusercontent.com/25277787/71318464-bebdd500-24d4-11ea-9303-08cfc2e191d4.png)

**Comment by EmirhaN998** [comment]
yea it does the same thing...

**Comment by osuplayer-hqquestion** [comment]
i get this issue also, ive tried reinstalling osu and hqOsu, and it doesn't fix

**Comment by MiclySlGa** [comment]
I'm trying to figure out someway to fix this problem.

**Comment by MiclySlGa** [comment]
Ok, after a few minutes searching in mpgh.net. Someone found a solution
go to:
https://www.dllme.com/dll/files/discord-rpc_dll.html

Download the dll and just put it on Osu directory.

**Comment by EmirhaN998** [comment]
> Ok, after a few minutes searching in mpgh.net. Someone found a solution
> go to:
> https://www.dllme.com/dll/files/discord-rpc_dll.html
> 
> Download the dll and just put it on Osu directory.

THANK YOU SO MUCH!!! IT WORKS NOW

**Comment by EmirhaN998** [comment]
> Ok, after a few minutes searching in mpgh.net. Someone found a solution
> go to:
> https://www.dllme.com/dll/files/discord-rpc_dll.html
> 
> Download the dll and just put it on Osu directory.

Now osu! Says Version Outdated...

**Comment by mastermust** [comment]
Having some trouble here finding osu! directory, if you could please tell me where that is.

**Comment by MiclySlGa** [comment]
> Having some trouble here finding osu! directory, if you could please tell me where that is.

Osu! Direcotry means you just open the osu file location and just paste it there. 
![image](https://user-images.githubusercontent.com/25277787/73836004-bbe32d80-4851-11ea-8025-1c87ef7721b0.png)
and yes. Ignore The "Hentai1" Drive

**Comment by sunsy7** [comment]
when i put dll file in osu directory, i launch hqosu, and osu outdated

**Comment by PermisosDev** [comment]
osu outdated
