### ISSUE TITLE
Osu update 20191226

### ISSUE THREAD

**Issue by MiclySlGa** [xxCherry/hqosu-legacy#20]
There was an update for osu.
Update 20191226
i looked more closely and i found no period or dot.
How do i change the config for this?
i tried deleting "Internal Version(number after dot)=" 
But it didn't work. Any ideas ?

**Comment by blue0831good** [comment]
Try deleting that line ??

**Comment by MiclySlGa** [comment]
i already said i tried deleting it, it didn't work as it still takes it as 20191226.5 stable fallback

**Comment by MXHARCOS** [comment]
But its annyoing and if i click too late i'll get banned..
I got banned a lot for it ,-,

**Comment by MiclySlGa** [comment]
i've never gotten banned used hqosu. It's your play style or you are just changing things in the config to make it look too weird.

I still need some help with the update of 20191226 stable.

[Cherry Stuff] (stable)
osu! version=20191226

is what in my config.ini
But it still takes it as 

[Cherry Stuff] (stable fallback)
osu! version=20191226
Internal Version(number after dot)=5

is there any way to remove internal version?
Since the stable version has no Internal Version atm.

**Comment by mastermust** [comment]
What is the osu directory, where do I put the discord file
