### ISSUE TITLE
Last update

### ISSUE THREAD

**Issue by Krusyar** [xxCherry/hqosu-legacy#26]
So, after a last update (Feb 7), there is no number after dot, what should i do to get the thing started? 
I can play offline, but in case with online, i need to "update" it, because without putting any letter "after dot" makes an error to appear:
 System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
 System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
 Class7.method_8(String string_1, Int32 int_0)
 Class7.method_9(String string_1, UInt32 uint_0)
 Class6.smethod_0(Boolean bool_8)
  hqOsu.Hax.Gate.OwO81H48RFRR58YAPVEQJPMN01C()
  #=qYgFvY1pQq_qWKGZ$F9XF1bcS504tECV$GTUMca08Atw=.#=ze$KT91E=()
Any help?

**Comment by zeisencloud** [comment]
put a 0 
osu! version=20200208
Internal Version(number after dot)=0 works for me

**Comment by Krusyar** [comment]
Yeah, my bad, for some reason i had another osu! version written down in config, while i remember i wrote down the correct one, anyway, thanks for the tip
