### ISSUE TITLE
closing after osu icon pop up

### ISSUE THREAD

**Issue by sofre1337** [xxCherry/hqosu-legacy#29]
so yeah the console is closing after osu icon pops up while launching and it doesnt work.

**Comment by MiclySlGa** [comment]
Does a osu updater shows up? if so check #18

**Comment by sofre1337** [comment]
no it doesnt

**Comment by MiclySlGa** [comment]
Hold on, i have to reinstall it

**Comment by sofre1337** [comment]
nvm yes it does ;d sorry it just opens for like 1/4 second and i didnt saw it 2 times

**Comment by MiclySlGa** [comment]
alright then
