### ISSUE TITLE
Do not click on notes

### ISSUE THREAD

**Issue by yukitteru** [xxCherry/hqosu-legacy#34]
Cheat suddenly stops clicking on notes. This problem is especially apparent in multiplayer. I tried "reload" - it does not help. What could be the problem?

**Comment by Hide-User** [comment]
@xxCherry

**Comment by yukitteru** [comment]
The problem is solved using fix-sync

**Comment by Hide-User** [comment]
Hi @yukitteru  can you explain to me how you did because i have this problem.

**Comment by yukitteru** [comment]
> Привет, @yukitteru. Ты можешь мне объяснить, как ты это сделал, потому что у меня есть эта проблема.

In the program write fix-sync

**Comment by Hide-User** [comment]
Thanks @yukitteru
