### ISSUE TITLE
Cant connect to kawata

### ISSUE THREAD

**Issue by AngelofDarknessEZPPFarm** [xxCherry/hqosu-legacy#37]
So i tried connecting to kawata but it says Connection failed. Will keep retrying. when using hqOsu and with the normal osu client it works perfectly fine.

**Comment by MiclySlGa** [comment]
I'm not sure, you could contact the developers of Kawata.

**Comment by AngelofDarknessEZPPFarm** [comment]
i just saw that kawata dosent support hqosu anymore because its old so yeah guess imma use Ainu client then
