### ISSUE TITLE
Online

### ISSUE THREAD

**Issue by lastedito** [xxCherry/hqosu-legacy#7]
It doesn't work online, says need to have osu on latest update to connect, when not using, everything works

**Comment by osugang** [comment]
change version in config

2019-09-04, tr, 16:22 lastedito <notifications@github.com> rašė:

**Comment by lastedito** [comment]
Alright thanks, the cherry thing is it ? And the game version is the thing to the extrem bottom ?

**Comment by MiclySlGa** [comment]
click on the config.ini, scroll down and you  will see osu!.version and Internal version go to https://osu.ppy.sh/home/changelog check the version (the latest has more players) so if the osu!version  on  the config different,  change the config version to the lastest one 
example:  osu! version=20190716
               Internal Version(number after dot)=5
Latest Version From  https://osu.ppy.sh/home/changelog :  20190906.1

Change  The Config :  Osu! Version=20190906
                                  internal Version(number after dot)=1
